import React, { useState, useCallback, useRef } from 'react';
import GameCanvas from './components/GameCanvas';
import UIOverlay from './components/UIOverlay';
import PhotoStudio from './components/PhotoStudio';
import { GameStats, Language } from './types';
import { VoxelEngine } from './services/VoxelEngine';
import { TRANSLATIONS } from './constants';

const SALT = "VOXEL_PET_SALT_KEY_2024";

const encrypt = (data: any): string => {
  try {
    const json = JSON.stringify(data);
    // Simple XOR obfuscation
    const xor = json.split('').map((c, i) =>
      String.fromCharCode(c.charCodeAt(0) ^ SALT.charCodeAt(i % SALT.length))
    ).join('');
    return btoa(xor);
  } catch (e) {
    console.error("Encryption failed", e);
    return "";
  }
};

const decrypt = (str: string): any => {
  try {
    const xor = atob(str);
    const json = xor.split('').map((c, i) =>
      String.fromCharCode(c.charCodeAt(0) ^ SALT.charCodeAt(i % SALT.length))
    ).join('');
    return JSON.parse(json);
  } catch (e) {
    console.error("Decryption failed", e);
    return null;
  }
};

const App: React.FC = () => {
  const [language, setLanguage] = useState<Language>('en');
  // Initial stats
  const [stats, setStats] = useState<GameStats>({
    hunger: 100,
    hygiene: 100,
    happiness: 100,
    energy: 100,
    weight: 50,
    isSleeping: false,
    isAlive: true,
    evolutionStage: 0,
    seed: "init",
    name: "Loading...",
    species: Math.random() > 0.5 ? 'pig' : 'chicken' // Initialize random species
  });

  const [modalOpen, setModalOpen] = useState<'export' | 'import' | null>(null);
  const [photoMode, setPhotoMode] = useState(false);
  const [saveCode, setSaveCode] = useState("");
  const [importError, setImportError] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);

  const engineRef = useRef<VoxelEngine | null>(null);

  const handleStatsUpdate = useCallback((newStats: GameStats) => {
    setStats(newStats);
  }, []);

  const handleEngineReady = useCallback((engine: VoxelEngine) => {
    engineRef.current = engine;
    // Initial fetch to sync stats
    setStats(engine.getStats());
  }, []);

  const handleAction = (action: 'feed' | 'clean' | 'play' | 'sleep' | 'exercise') => {
    if (!engineRef.current) return;
    
    switch (action) {
      case 'feed': engineRef.current.feed(); break;
      case 'clean': engineRef.current.clean(); break;
      case 'play': engineRef.current.play(); break;
      case 'sleep': engineRef.current.sleep(); break;
      case 'exercise': engineRef.current.startExercise(); break;
    }
  };

  const handleNewPet = () => {
    if (!engineRef.current) return;
    const newSeed = Math.random().toString(36).substring(7);
    const randomSpecies = Math.random() > 0.5 ? 'pig' : 'chicken';
    
    const newStats: GameStats = {
      hunger: 80,
      hygiene: 100,
      happiness: 80,
      energy: 100,
      weight: 50,
      isSleeping: false,
      isAlive: true,
      evolutionStage: 0,
      seed: newSeed,
      name: "...", // Will be generated by engine
      species: randomSpecies
    };
    engineRef.current.loadState(newStats);
  };

  const handleExport = () => {
     if (!engineRef.current) return;
     const currentStats = engineRef.current.getStats();
     const code = encrypt(currentStats);
     setSaveCode(code);
     setModalOpen('export');
     setCopySuccess(false);
  };

  const handleImport = () => {
      setSaveCode("");
      setImportError(false);
      setModalOpen('import');
  };

  const handleTogglePhoto = () => {
      if (!engineRef.current) return;
      const isEntering = !photoMode;
      setPhotoMode(isEntering);
      engineRef.current.setPhotoMode(isEntering);
  };

  const confirmImport = () => {
      const data = decrypt(saveCode);
      if (data && data.seed && engineRef.current) {
          engineRef.current.loadState(data);
          setModalOpen(null);
      } else {
          setImportError(true);
      }
  };

  const copyToClipboard = () => {
      navigator.clipboard.writeText(saveCode);
      setCopySuccess(true);
  };

  const t = TRANSLATIONS[language];

  return (
    <div className="relative w-full h-full overflow-hidden bg-sky-200">
      <GameCanvas 
        onStatsUpdate={handleStatsUpdate} 
        onEngineReady={handleEngineReady} 
      />
      
      {photoMode && engineRef.current ? (
          <PhotoStudio 
            stats={stats}
            language={language}
            onClose={handleTogglePhoto}
            engine={engineRef.current}
          />
      ) : (
          <UIOverlay 
            stats={stats} 
            language={language} 
            onLanguageChange={setLanguage}
            onAction={handleAction}
            onNewPet={handleNewPet}
            onExport={handleExport}
            onImport={handleImport}
            onPhoto={handleTogglePhoto}
          />
      )}

      {/* Modal */}
      {modalOpen && (
        <div className="absolute inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-xl shadow-2xl p-6 w-full max-w-md border-4 border-gray-800">
                <h2 className="text-2xl font-black mb-4 text-gray-800">
                    {modalOpen === 'export' ? t.export : t.import} {t.saveCode}
                </h2>
                
                {modalOpen === 'export' ? (
                    <>
                        <textarea 
                            readOnly 
                            className="w-full h-32 p-2 bg-gray-100 border-2 border-gray-300 rounded mb-4 font-mono text-xs break-all resize-none focus:outline-none"
                            value={saveCode}
                        />
                        <div className="flex justify-between">
                             <button 
                                onClick={copyToClipboard}
                                className={`font-bold py-2 px-4 rounded border-2 border-black transition-colors ${copySuccess ? 'bg-green-400 text-white' : 'bg-yellow-400 hover:bg-yellow-500'}`}
                             >
                                {copySuccess ? t.copied : t.copy}
                             </button>
                             <button 
                                onClick={() => setModalOpen(null)}
                                className="bg-gray-200 hover:bg-gray-300 font-bold py-2 px-4 rounded border-2 border-black"
                             >
                                {t.close}
                             </button>
                        </div>
                    </>
                ) : (
                    <>
                        <textarea 
                            className="w-full h-32 p-2 bg-white border-2 border-blue-300 rounded mb-2 font-mono text-xs break-all resize-none focus:outline-blue-500"
                            value={saveCode}
                            onChange={(e) => setSaveCode(e.target.value)}
                            placeholder={t.placeholder}
                        />
                        {importError && <p className="text-red-500 font-bold text-sm mb-2">{t.importError}</p>}
                        <div className="flex justify-between">
                             <button 
                                onClick={confirmImport}
                                className="bg-green-400 hover:bg-green-500 text-white font-bold py-2 px-4 rounded border-2 border-black shadow"
                             >
                                {t.import}
                             </button>
                             <button 
                                onClick={() => setModalOpen(null)}
                                className="bg-gray-200 hover:bg-gray-300 font-bold py-2 px-4 rounded border-2 border-black shadow"
                             >
                                {t.close}
                             </button>
                        </div>
                    </>
                )}
            </div>
        </div>
      )}
    </div>
  );
};

export default App;