import { Localizations } from './types';

export const COLORS = {
  background: 0x87CEEB, // Sky Blue
  ground: 0x8BC34A,     // Vibrant Green
  groundDark: 0x689F38, 
  poop: 0x795548,       // Brown
  food: 0xFFD54F,       // Corn Yellow
  stone: 0x90A4AE,
};

export const CHICKEN_PALETTES = [
    { name: 'Classic White', body: 0xFFFFFF, sec: 0xFFD54F, comb: 0xFF5252 },
    { name: 'Golden Hen', body: 0xFFA726, sec: 0xFFE0B2, comb: 0xD84315 },
    { name: 'Void Chicken', body: 0x263238, sec: 0x455A64, comb: 0xAB47BC },
    { name: 'Sakura', body: 0xF8BBD0, sec: 0xF48FB1, comb: 0xEC407A },
    { name: 'Sky Walker', body: 0xE1F5FE, sec: 0x81D4FA, comb: 0x0288D1 },
    { name: 'Choco', body: 0x5D4037, sec: 0x8D6E63, comb: 0xFF7043 },
    { name: 'Minty', body: 0xB2DFDB, sec: 0x80CBC4, comb: 0x009688 },
];

export const PIG_PALETTES = [
    { name: 'Classic Pink', body: 0xF48FB1, sec: 0xF8BBD0, nose: 0xEC407A },
    { name: 'Muddy', body: 0x8D6E63, sec: 0xA1887F, nose: 0x5D4037 },
    { name: 'Spotted', body: 0xFFFFFF, sec: 0x333333, nose: 0xF48FB1 },
    { name: 'Golden Truffle', body: 0xFFD54F, sec: 0xFFECB3, nose: 0xFFA000 },
    { name: 'Wild Boar', body: 0x4E342E, sec: 0x3E2723, nose: 0x8D6E63 },
    { name: 'Lavender', body: 0xCE93D8, sec: 0xE1BEE7, nose: 0x8E24AA },
    { name: 'Matcha', body: 0xC5E1A5, sec: 0xDCEDC8, nose: 0x689F38 },
];

export const TRANSLATIONS: Localizations = {
  en: {
    title: "Bored Tamagotchi",
    hunger: "Hunger",
    hygiene: "Hygiene",
    happiness: "Joy",
    energy: "Energy",
    weight: "Weight",
    feed: "Feed",
    clean: "Clean",
    play: "Play",
    exercise: "Train",
    sleep: "Sleep",
    wake: "Wake",
    dead: "Left the farm...",
    evolved: "Grown Up!",
    newPet: "New Egg",
    export: "Save",
    import: "Load",
    saveCode: "Save Code",
    copy: "Copy",
    close: "Close",
    importError: "Invalid Code!",
    copied: "Copied!",
    placeholder: "Paste save code here...",
    photoMode: "Photo Studio",
    snap: "Snap",
    rotate: "Rotate",
    download: "Save Card",
    shareTitle: "My Voxel Pet",
    exerciseInstruction: "Move cursor to lead pet!",
  },
  "zh-TW": {
    title: "無聊電子雞",
    hunger: "飽食",
    hygiene: "清潔",
    happiness: "心情",
    energy: "體力",
    weight: "體重",
    feed: "餵食",
    clean: "打掃",
    play: "玩耍",
    exercise: "運動",
    sleep: "睡覺",
    wake: "叫醒",
    dead: "離家出走了...",
    evolved: "長大了!",
    newPet: "新夥伴",
    export: "存檔",
    import: "讀檔",
    saveCode: "存檔代碼",
    copy: "複製",
    close: "關閉",
    importError: "代碼無效!",
    copied: "已複製!",
    placeholder: "在此貼上存檔代碼...",
    photoMode: "攝影棚",
    snap: "拍照",
    rotate: "旋轉",
    download: "保存卡片",
    shareTitle: "我的像素寵物",
    exerciseInstruction: "移動手指來引導寵物跑步！",
  },
  ja: {
    title: "退屈なたまごっち",
    hunger: "満腹度",
    hygiene: "清潔さ",
    happiness: "機嫌",
    energy: "元気",
    weight: "体重",
    feed: "ごはん",
    clean: "そうじ",
    play: "あそぶ",
    exercise: "運動",
    sleep: "ねる",
    wake: "おきる",
    dead: "家出した...",
    evolved: "進化!",
    newPet: "新しい卵",
    export: "保存",
    import: "読込",
    saveCode: "セーブコード",
    copy: "コピー",
    close: "閉じる",
    importError: "無効なコード!",
    copied: "コピー完了!",
    placeholder: "ここにコードを貼り付け...",
    photoMode: "撮影スタジオ",
    snap: "撮影",
    rotate: "回転",
    download: "カード保存",
    shareTitle: "私のボクセルペット",
    exerciseInstruction: "カーソルを動かして走らせよう！",
  },
};

export const STAT_DECAY_RATE = 0.05; 
export const EVOLUTION_THRESHOLD_TIME = 60000;